name: typed_messages
description: A simple piece of data with encoder and decoder
repository: https://github.com/Davenchy/typed_messages
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
